### ISSUE TITLE
Explain how to use this?

### ISSUE THREAD

**Issue by Ptival** [tazjin/yants#2]
All your examples assume that the library is already in scope.

Are you just supposed to:
```
with (import /path/to/yants/default.nix {});
... 
```
?

**Comment by tazjin** [comment]
Yes, that's one option!

The primary ones are probably these (all assuming we are in the `yants` folder):

1. Import into scope with `with`:
    ```nix
    with (import ./default.nix {});
    # ... Nix code that uses yants ... 
    ```

2. Import as a named variable:
    ```nix
    let yants = import ./default.nix {};
    in yants.string "foo" # or other uses ...
    ````

3. Overlay into `pkgs.lib`:
    ```nix
    # wherever you import your package set (e.g. from <nixpkgs>):
    import <nixpkgs> {
      overlays = [
        (self: super: {
          lib = super.lib // { yants = import ./default.nix { inherit (super) lib; }; };
        })
      ];
    }

    # yants now lives at lib.yants, besides the other library functions!
    ```

There is some more generic information about Nix the language [in my Nix one-pager](https://github.com/tazjin/nix-1p).

**Comment by Ptival** [comment]
Yeah, I chose option #2 for my project, since it helps my linter figure out identifiers that are not in scope.

This was just a suggestion to add this to the README so that first-time users know what to do.
Thanks for the library, it's useful!

**Comment by tazjin** [comment]
Makes sense, I've added it to the README!

> it's useful

I'd be interested in your use-case if you care to share! There are some possible improvements to the current API and feature set, but I'd like to know what people actually do/want to do to prioritise them.

**Comment by Ptival** [comment]
My use case is using nix as query language to get information about packages in nixpkgs. I need to interface with a Haskell program, and so I really care about my structs having the proper fields, especially as I make changes to the interface between nix and Haskell code!

I will make additional pull requests for things I'd find useful that are missing.
